### PR TITLE
Adds a 'not equals' clause

### PR DESCRIPTION
**Pull request by mrtom**
This PR attempts to add a 'not equals' clause - although I've no idea how to run the tests so it's yolo'd by eye only. Be warned!

Hopefully it's a pretty trivial change tho?

### CODE REVIEW

**Comment by lolopinto** [comment]
can you also add it to https://github.com/lolopinto/ent/blob/main/ts/src/index.ts#L93 so that it's easily accessible?

**Comment by lolopinto** [comment]
Oh, can you also update https://github.com/lolopinto/ent/blob/main/docs/docs/advanced-topics/clause.md?

**Comment by mrtom** [comment]
Done!

**Comment by lolopinto** [comment]
now available in @snowtop/ent@0.0.6

**Pull request merged**
